updated to new KNP
bcgov/issuer-kit-demo-verifier-chat pull request #24
Opened 2021-03-03 19:27 UTC by wadeking98

2021-03-03 23:22 UTC, esune requested changes
A couple of tweaks are required.

Additionally, I would suggest the client base build and the server build are updated to use Artifactory: the server is already setup correctly, you only need to add the artifactory prefix to the `SOURCE_IMAGE_NAME` parameter.

The client build needs to be updated to follow the same pattern.

2021-03-03 23:22 UTC, esune commented on openshift/templates/nsp/build.yaml
> +        - - ext:name=internet-build-resources
Outdated: needs to be in the new KNP format

2021-03-05 18:49 UTC, wadeking98 commented on openshift/templates/nsp/build.yaml
> +        - - ext:name=internet-build-resources
changed to recommended exaple by Wade Barnes

2021-03-05 21:17 UTC, esune commented on openshift/templates/client/client-deploy.dev.param
> +APPLICATION_DOMAIN=pctftest-dev.apps.silver.devops.gov.bc.ca
The `vonx.io` URLs should be retained for dev and test as well

2021-03-05 22:53 UTC, wadeking98 commented on openshift/templates/client/client-deploy.dev.param
> +APPLICATION_DOMAIN=pctftest-dev.apps.silver.devops.gov.bc.ca
reverted to vonx.io

2021-03-08 16:16 UTC, WadeBarnes requested changes
See comments and suggestions.

2021-03-08 16:16 UTC, WadeBarnes commented on openshift/templates/server/server-build.param
> +SOURCE_IMAGE_NAME=docker-remote.artifacts.developer.gov.bc.ca/centos/nodejs-12-centos7
There is a feely available UBI replacement for this; `registry.access.redhat.com/ubi8/nodejs-12`

```suggestion
SOURCE_IMAGE_NAME=registry.access.redhat.com/ubi8/nodejs-12
```

2021-03-08 16:16 UTC, WadeBarnes commented on openshift/templates/server/server-build.yaml
> +    value: docker-remote.artifacts.developer.gov.bc.ca/centos/nodejs-12-centos7
```suggestion
    value: registry.access.redhat.com/ubi8/nodejs-12
```

2021-03-08 17:35 UTC, closed without merging

2021-03-08 17:36 UTC, wadeking98 commented
dco complaining about a 3 way merge, going to close and re open PR